### ISSUE TITLE
Progressively enhanced isomorphism

### ISSUE THREAD

**Issue by cmgriffing** [mdressman/isomorphic-porch-demo#2]
Hi Matt,
I enjoyed your talk at the Seattle React meetup.

I started wondering if there was a way to render the app so that even users with JS disabled could interact with the form. It isn't necessarily something that a whole app should have to rely on, but it might be useful for certain key functionality in some apps.

I created a pull request on the porchdotcom repo: https://github.com/porchdotcom/isomorphic-porch-demo/pull/2

It almost works completely except for there not being a redirect back to the home page after url-encoded form submission. However, you can click back after and see the new item added to the list, so it is a step in the right direction.

I would be interested in hearing your thoughts and criticisms. The code is obviously a bit of a hack, but a proper solution is definitely possible.

Thanks.

ps: I wasn't sure how often you or others might check the porchdotcom account with regards to this repo, so I thought it was a good idea just to raise an issue here as well. Sorry for any inconvenience.

**Comment by mdressman** [comment]
Thanks so much for submitting a PR!  I will check it out and get back to you.  Cheers!

**Comment by cmgriffing** [comment]
I'm going through and cleaning up my lingering Issues. BTW, I really liked this demo when it was presented at SeattleJS years ago.
